# Use CentOS base image
FROM centos
MAINTAINER George Sapkin, george.sapkin@gmail.com

# Update image
# RUN yum update -y

# Install Foundation DB 2.0.4 client
RUN yum install -y https://foundationdb.com/downloads/I_accept_the_FoundationDB_Community_License_Agreement/2.0.4/foundationdb-clients-2.0.4-1.x86_64.rpm
